apiVersion: apps/v1
kind: Deployment
metadata:
  name: flightctl-ui
  namespace: {{ .Values.flightctlUi.namespace }}
  labels:
    app: flightctl-ui
    role: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flightctl-ui
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flightctl-ui
        role: frontend
    spec:
      containers:
        - env:
          - name: BACKEND_KEYCLOAK_AUTHORITY
            valueFrom:
              secretKeyRef:
                name: flightctl-ui
                key: BACKEND_KEYCLOAK_AUTHORITY
          - name: KEYCLOAK_AUTHORITY
            valueFrom:
              secretKeyRef:
                name: flightctl-ui
                key: KEYCLOAK_AUTHORITY
          - name: KEYCLOAK_CLIENTID
            valueFrom:
              secretKeyRef:
                name: flightctl-ui
                key: KEYCLOAK_CLIENTID
          - name: KEYCLOAK_REDIRECT
            valueFrom:
              secretKeyRef:
                name: flightctl-ui
                key: KEYCLOAK_REDIRECT
          - name: KEYCLOAK_SECRET
            valueFrom:
              secretKeyRef:
                name: flightctl-ui
                key: KEYCLOAK_SECRET
          - name: API_PORT
            value: '8080'
          - name: FLIGHTCTL_SERVER
            valueFrom:
              secretKeyRef:
                name: flightctl-ui
                key: FLIGHTCTL_SERVER
          - name: FLIGHTCTL_METRICS_SERVER
            valueFrom:
              secretKeyRef:
                name: flightctl-ui
                key: FLIGHTCTL_METRICS_SERVER
          - name: BOOTC_IMG_URL
            valueFrom:
              secretKeyRef:
                name: flightctl-ui
                key: BOOTC_IMG_URL
          - name: QCOW2_IMG_URL
            valueFrom:
              secretKeyRef:
                name: flightctl-ui
                key: QCOW2_IMG_URL
          image: {{ .Values.flightctlUi.image }}
          name: flightctl-ui
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /app/certs
              name: flightctl-ui-certs
      restartPolicy: Always
      volumes:
        - name: flightctl-ui-certs
          secret:
            secretName: flightctl-ui-certs
            items:
              - key: api-sig.key
                path: api-sig.key
              - key: ca.crt
                path: ca.crt
              - key: front-cli.crt
                path: front-cli.crt
              - key: front-cli.key
                path: front-cli.key
